In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

**Working with Dates**

In [7]:
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. Extract Year

In [9]:
date['date_year']=date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
565 2019-04-29         888       20       5       2019
629 2019-01-15        7138       28       1       2019
442 2019-06-04         963       13       1       2019
745 2019-05-18        6910       21       1       2019
4   2019-01-06        4344       25       3       2019

2.Extract Month

In [10]:
date['date_month_no']=date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  date_year  date_month_no
882 2019-10-14        5666       25       2       2019             10
291 2018-11-20        5009       28      12       2018             11
50  2019-06-07        6137        3       3       2019              6
395 2019-08-06        7300        9      46       2019              8
426 2019-11-01        6487       30       6       2019             11

In [11]:
date['date_month_name'] = date['date'].dt.month_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

3.Extract Days

In [12]:
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [13]:
#day of week
date['day_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,day_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [14]:
# day of week name
date['date_dow_name']= date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,day_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [15]:
# is weekwnd?
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,day_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

Extract week of the year

In [23]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,day_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

Extract Quater

In [22]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,day_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

Extract Semester

In [20]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,day_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

**Extract Time elapsed between dates**

In [24]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 9, 5, 21, 18, 42, 18549)

In [25]:
today - date['date']

0     2461 days 21:18:42.018549
1     2943 days 21:18:42.018549
2     2874 days 21:18:42.018549
3     2576 days 21:18:42.018549
4     2799 days 21:18:42.018549
                 ...
995   2889 days 21:18:42.018549
996   2830 days 21:18:42.018549
997   2678 days 21:18:42.018549
998   2743 days 21:18:42.018549
999   2517 days 21:18:42.018549
Name: date, Length: 1000, dtype: timedelta64[ns]

In [26]:
(today - date['date']).dt.days

0      2461
1      2943
2      2874
3      2576
4      2799
       ...
995    2889
996    2830
997    2678
998    2743
999    2517
Name: date, Length: 1000, dtype: int64

In [29]:
# Months passed
months_passed = np.round(
    (today - date['date']) / np.timedelta64(30, 'D'),
    0
)
months_passed

0      82.0
1      98.0
2      96.0
3      86.0
4      93.0
       ...
995    96.0
996    94.0
997    89.0
998    91.0
999    84.0
Name: date, Length: 1000, dtype: float64

In [30]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [31]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [32]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [33]:
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

**Extract Time part**

In [34]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23:11:00

In [35]:
# Time difference
today - time['date']

0     4647 days 20:28:42.018549
1     4511 days 21:38:42.018549
2     4997 days 20:57:42.018549
3     4299 days 20:47:42.018549
4     4696 days 22:07:42.018549
                 ...
995   5286 days 20:28:42.018549
996   4607 days 22:04:42.018549
997   5072 days 21:41:42.018549
998   5188 days 21:44:42.018549
999   4460 days 21:53:42.018549
Name: date, Length: 1000, dtype: timedelta64[ns]

In [36]:
# in seconds
(today - time['date'])/np.timedelta64(1,'s')

0      4.015745e+08
1      3.898283e+08
2      4.318163e+08
3      3.715085e+08
4      4.058141e+08
           ...
995    4.567841e+08
996    3.981243e+08
997    4.382989e+08
998    4.483215e+08
999    3.854228e+08
Name: date, Length: 1000, dtype: float64

In [37]:
# in minutes
(today - time['date'])/np.timedelta64(1,'m')

0      6.692909e+06
1      6.497139e+06
2      7.196938e+06
3      6.191808e+06
4      6.763568e+06
           ...
995    7.613069e+06
996    6.635405e+06
997    7.304982e+06
998    7.472025e+06
999    6.423714e+06
Name: date, Length: 1000, dtype: float64

In [38]:
# in hours
(today - time['date'])/np.timedelta64(1,'h')

0      111548.478338
1      108285.645005
2      119948.961672
3      103196.795005
4      112726.128338
           ...
995    126884.478338
996    110590.078338
997    121749.695005
998    124533.745005
999    107061.895005
Name: date, Length: 1000, dtype: float64