In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [3]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1
3  35.0       1      1      0         1
4  35.0       3      0      0         0

In [4]:
df.isnull().mean()

Age         0.198653
Pclass      0.000000
SibSp       0.000000
Parch       0.000000
Survived    0.000000
dtype: float64

In [5]:
df.dropna(inplace=True)

In [6]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [8]:
X.head()

    Age  Pclass  SibSp  Parch
0  22.0       3      1      0
1  38.0       1      1      0
2  26.0       3      0      0
3  35.0       1      1      0
4  35.0       3      0      0

In [9]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6933333333333332)

**Applying Feature Construction**

In [10]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [11]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  22.0       3      1      0            2
1  38.0       1      1      0            2
2  26.0       3      0      0            1
3  35.0       1      1      0            2
4  35.0       3      0      0            1

In [12]:
def myfunc(num):
    if num == 1:  #alone
        return 0
    elif num > 1 and num <= 4:  #small family
        return 1
    else:    #Large Family
        return 2

In [13]:
myfunc(4)

1

In [14]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [15]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  22.0       3      1      0            2            1
1  38.0       1      1      0            2            1
2  26.0       3      0      0            1            0
3  35.0       1      1      0            2            1
4  35.0       3      0      0            1            0

In [17]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [18]:
X.head()

    Age  Pclass  Family_type
0  22.0       3            1
1  38.0       1            1
2  26.0       3            0
3  35.0       1            1
4  35.0       3            0

In [20]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)